[package]
name = "process"
version = "0.1.0"
edition = "2021"

[dependencies]
interprocess = "2.2.0"
winapi = { version = "0.3.9", features = ["winbase", "processthreadsapi", "synchapi", "namedpipeapi", "handleapi"] }
